name: place_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0
  provider: ^6.0.2
  uuid: ^3.0.4
  go_router: ^6.0.0
  collection: ^1.16.0
  location: ^2.5.4
  geocoder: any
  intl: ^0.18.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0

dev_dependencies:
  analysis_defaults:
    path: analysis_defaults/
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true
